version: "3.8"
services:
  api:
    environment:
      - API_WORKERS=2
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - diarizer-cache:/data/diarizer_cache
      - hf-cache:/hf_cache
      - ./app.db:/app/app.db
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file: .env
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - diarizer-cache:/data/diarizer_cache
      - /path/to/hf_cache_host:/hf_cache:rw
    depends_on:
      - redis
    command:
      ["celery", "-A", "celery_app", "worker",
       "--loglevel=info",
       "--concurrency=${CPU_CONCURRENCY}",
       "--queues=preprocess_cpu",
       "--prefetch-multiplier=1"]
    restart: unless-stopped

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NVIDIA_VISIBLE_DEVICES=all
    env_file: .env
    runtime: nvidia
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - diarizer-cache:/data/diarizer_cache
      - ctranslate2-cache:/root/.cache/ctranslate2
      - /path/to/hf_cache_host:/hf_cache:rw
    depends_on:
      - redis
    command:
      ["celery", "-A", "celery_app", "worker",
       "--loglevel=info",
       "--concurrency=1",
       "--queues=preprocess_gpu",
       "--prefetch-multiplier=1"]
    restart: unless-stopped

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    command: ["celery", "-A", "celery_app", "beat", "--loglevel=info"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
    restart: unless-stopped

  flower:
    image: mher/flower:0.9.7
    entrypoint: ["celery"]
    env_file: .env
    ports:
      - "5555:5555"
    command:
      - flower
      - "--broker=${CELERY_BROKER_URL}"
      - "--basic_auth=${FLOWER_USER}:${FLOWER_PASS}"
      - "--port=5555"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      retries: 3

  # GPU-мониторинг (dcgm-exporter) убран, чтобы избежать ошибок с несуществующими тегами.
  # Если нужен, раскомментируйте и подставьте актуальный существующий тег.
  # dcgm-exporter:
  #   image: nvidia/dcgm-exporter:2.6.13-2.6.13-ubi8
  #   runtime: nvidia
  #   environment:
  #     - DCGM_EXPORTER_EXPORT_PER_PROCESS_METRICS=true
  #   ports:
  #     - "9400:9400"
  #   depends_on:
  #     - gpu-worker
  #   restart: unless-stopped

volumes:
  upload-data:
  results-data:
  diarizer-cache:
  ctranslate2-cache:
  hf-cache:
  redis-data: