version: "3.8"

services:
  redis:
    image: redis:7-alpine

  tusd:
    image: tusproject/tusd:2.2.3
    ports:
      - "1080:1080"

  api:
    build:
      context: .
      target: base
    command: >
      uvicorn main:app
      --host ${FASTAPI_HOST}
      --port ${FASTAPI_PORT}
      --workers ${API_WORKERS}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - upload-data:${UPLOAD_FOLDER}
    depends_on:
      - redis
      - tusd

  cpu-worker:
    build:
      context: .
      target: base
    command: >
      celery -A celery_app.celery_app worker
      --hostname=cpu@%h
      --concurrency=${CPU_CONCURRENCY}
      --queues=preprocess_cpu
    volumes:
      - upload-data:${UPLOAD_FOLDER}
      - hf_cache:/hf_cache
    depends_on:
      - redis

  gpu-worker:
    build:
      context: .
      target: base
    runtime: nvidia
    command: >
      celery -A celery_app.celery_app worker
      --hostname=gpu@%h
      --concurrency=${GPU_CONCURRENCY}
      --queues=preprocess_gpu
    volumes:
      - upload-data:${UPLOAD_FOLDER}
      - hf_cache:/hf_cache
    depends_on:
      - redis

volumes:
  upload-data:
  hf_cache: