version: "3.8"

volumes:
  hf_cache:
  upload-data:

services:
  redis:
    image: redis:7-alpine

  api:
    build: .
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --workers
      - "${API_WORKERS}"

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - hf_cache:/hf_cache
    depends_on:
      - redis
    command:
      - celery
      - -A
      - celery_app.app
      - worker
      - --concurrency=${CELERY_CONCURRENCY}
      - --hostname=cpu-worker
      - --queues=preprocess_cpu,default

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - hf_cache:/hf_cache
    depends_on:
      - redis
    command:
      - celery
      - -A
      - celery_app.app
      - worker
      - --concurrency=1
      - --hostname=gpu-worker
      - --queues=preprocess_gpu,default

# no extra services needed here