version: "3.8"

services:
  # Redis для брокера и backend-а Celery
  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  # tusd (TUS upload server)
  tusd:
    image: tusproject/tusd:v1.1.1
    command:
      - tusd
      - -host=0.0.0.0
      - -port=1080
      - -upload-dir=/data
      - -cors=*
    ports:
      - "1080:1080"
    restart: unless-stopped
    volumes:
      - upload-data:/data

  # Flower UI для мониторинга Celery
  flower:
    image: mher/flower:latest
    command:
      - flower
      - --port=5555
      - --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    restart: unless-stopped
    depends_on:
      - redis

  # FastAPI + Uvicorn
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - API_WORKERS=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      # … остальные переменные из .env …
    volumes:
      - upload-data:/app/uploads
      - hf_cache:/hf_cache
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - tusd

  # Celery worker для CPU (диаризация)
  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - celery
      - -A
      - celery_app.celery_app
      - worker
      - --loglevel=info
      - --concurrency=1
      - --hostname=cpu-worker
      - --queues=preprocess_cpu
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      # … остальные из .env …
    volumes:
      - upload-data:/app/uploads
      - hf_cache:/hf_cache
    depends_on:
      - redis
      - tusd

  # Celery worker для GPU (chunked-Whisper)
  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command:
      - celery
      - -A
      - celery_app.celery_app
      - worker
      - --loglevel=info
      - --concurrency=1
      - --hostname=gpu-worker
      - --queues=preprocess_gpu
    deploy:
      resources:
        limits:
          memory: 4g
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      # … остальные из .env …
    volumes:
      - upload-data:/app/uploads
      - hf_cache:/hf_cache
    depends_on:
      - redis
      - tusd

volumes:
  upload-data:
  redis-data:
  hf_cache: