version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - tusd
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --workers ${API_WORKERS}"

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-cpu-worker
    env_file: .env
    depends_on:
      - redis
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      - diarizer-cache:/tmp/diarizer_cache
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency ${CPU_CONCURRENCY}
      --hostname cpu-worker
      --queues preprocess_cpu

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: proxyai-gpu-worker
    env_file: .env
    depends_on:
      - redis
    runtime: nvidia
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      # Bind-mount your host’s HF cache (RW) so quantized files get persisted:
      - /path/to/hf_cache_host:/hf_cache:rw
      - ctranslate2-cache:/root/.cache/ctranslate2
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency ${GPU_CONCURRENCY}
      --hostname gpu-worker
      --queues preprocess_gpu

  redis:
    image: redis:7-alpine
    container_name: proxyai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  tusd:
    image: tusproject/tusd:latest
    container_name: proxyai-tusd
    ports:
      - "1080:1080"
    command:
      - tusd
      - --host=0.0.0.0
      - --port=1080
      - --dir=/data
    volumes:
      - upload-data:/data

volumes:
  upload-data:
  results-data:
  diarizer-cache:
  ctranslate2-cache:
  redis-data: