version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxyai_net

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - proxyai_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      # теперь берём пользователя и БД из тех же переменных, что создаются в сервисе db
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - API_WORKERS
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - diarizer-cache:/data/diarizer_cache
      - /path/to/hf_cache_host:/hf_cache:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
    networks:
      - proxyai_net

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - WHISPER_DEVICE=cpu
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - /path/to/hf_cache_host:/data/diarizer_cache:ro
      - /path/to/hf_cache_host:/hf_cache:rw
    depends_on:
      - db
      - redis
    command:
      ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=${CPU_CONCURRENCY}"]
    restart: unless-stopped
    networks:
      - proxyai_net

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NVIDIA_VISIBLE_DEVICES=all
      - WHISPER_DEVICE=cuda
    runtime: nvidia
    volumes:
      - upload-data:/data/uploads
      - results-data:/data/results
      - diarizer-cache:/data/diarizer_cache
      - ctranslate2-cache:/root/.cache/ctranslate2
      - /path/to/hf_cache_host:/hf_cache:rw
    depends_on:
      - db
      - redis
    command:
      ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=${GPU_CONCURRENCY}", "--queues=preprocess_gpu"]
    restart: unless-stopped
    networks:
      - proxyai_net

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    command:
      ["celery", "-A", "tasks", "beat", "--loglevel=info"]
    restart: unless-stopped
    networks:
      - proxyai_net

  flower:
    image: mher/flower:0.9.7
    env_file: .env
    ports:
      - "5555:5555"
    command:
      - flower
      - "--broker=${CELERY_BROKER_URL}"
      - "--basic_auth=${FLOWER_USER}:${FLOWER_PASS}"
      - "--port=5555"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      retries: 3
    networks:
      - proxyai_net

volumes:
  postgres_data:
  redis-data:
  upload-data:
  results-data:
  diarizer-cache:
  ctranslate2-cache:
  hf-cache:

networks:
  proxyai_net:
    driver: bridge