version: "3.8"

services:
  tusd:
    image: tusproject/tusd:latest
    ports:
      - "1080:1080"
    command: ["tusd", "--upload-dir", "/files"]
    volumes:
      - upload-data:/files

  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - ./static:/app/static:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 5s
      retries: 5

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency=${CELERY_CONCURRENCY}
      -Q preprocess_cpu
    depends_on:
      - redis
    volumes:
      - hf_cache:/hf_cache

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file: .env
    runtime: nvidia
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency=${WORKER_GPU_CONCURRENCY:-1}
      -Q preprocess_gpu
    depends_on:
      - redis
    volumes:
      - hf_cache:/hf_cache

  flower:
    image: mher/flower:1.0.0
    ports:
      - "5555:5555"
    command: ["flower", "--port=5555", "--broker=${CELERY_BROKER_URL}"]

  integration-test:
    image: python:3.10-slim
    depends_on:
      api:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app:cached
    env_file: .env
    entrypoint: ["pytest", "-q", "tests/test_integration.py"]
    restart: "no"

volumes:
  upload-data:
  hf_cache: