version: "3.8"

services:
  # -------- TUSD (resumable upload server) ----------
  tusd:
    image: tusproject/tusd:latest
    ports:
      - "1080:1080"
    command: ["tusd", "--upload-dir", "/files"]
    volumes:
      - upload-data:/files

  # -------- Redis (broker + backend) ----------
  redis:
    image: redis:7-alpine

  # -------- FastAPI / frontend & backend ----------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - upload-data:${UPLOAD_FOLDER}
    depends_on:
      - redis
      - tusd

  # -------- CPU worker (diarization) ----------
  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      celery -A celery_app.celery_app worker
      --loglevel=INFO
      --concurrency=${CELERY_CONCURRENCY}
      --queues preprocess_cpu
      --hostname=cpu-worker@%h
    volumes:
      - upload-data:${UPLOAD_FOLDER}
      - hf_cache:/root/.cache/huggingface/hub
    depends_on:
      - redis
      - api

  # -------- GPU worker (chunked Whisper) ----------
  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file:
      - .env
    command: >
      celery -A celery_app.celery_app worker
      --loglevel=INFO
      --concurrency=${GPU_CONCURRENCY}
      --queues preprocess_gpu
      --hostname=gpu-worker@%h
    volumes:
      - upload-data:${UPLOAD_FOLDER}
      - hf_cache:/root/.cache/huggingface/hub
    depends_on:
      - redis
      - api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # -------- Flower (monitoring) ----------
  flower:
    image: mher/flower:latest
    command: ["flower", "--port=5555", "--broker=${CELERY_BROKER_URL}"]
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  upload-data:
  hf_cache: