version: "3.8"

services:
  redis:
    image: "redis:7-alpine"
    container_name: proxyai-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  tusd:
    image: "tusproject/tusd:latest"
    container_name: proxyai-tusd
    command: ["tusd", "--dir", "/files", "--no-implicit-create-dir"]
    ports:
      - "1080:1080"
    volumes:
      - upload-data:/files

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-api
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - redis
      - tusd
    volumes:
      - upload-data:/tmp/uploads
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port ${FASTAPI_PORT}

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - upload-data:/tmp/uploads
    command: >
      celery -A celery_app worker
      --loglevel=info

volumes:
  redis-data:
  upload-data: