version: "3.8"
services:
  api:
    build:
      context: .
      target: cpu
    ports:
      - "${API_PORT}:8000"

  cpu-worker:
    build:
      context: .
      target: cpu
    command: celery -A celery_app.celery_app worker --queue=preprocess_cpu --concurrency=${CELERY_CONCURRENCY}

  gpu-worker:
    build:
      context: .
      target: gpu
    runtime: nvidia
    command: celery -A celery_app.celery_app worker --queue=preprocess_gpu --concurrency=1

  redis:
    image: redis:7-alpine

  tusd:
    image: tus/tusd:latest
    ports:
      - "1080:1080"

  flower:
    image: mher/flower:latest
    command: flower --broker=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"

volumes:
  hf_cache:
    driver: local