version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-api
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
    depends_on:
      - redis
      - tusd
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn main:app
              --host 0.0.0.0
              --port ${FASTAPI_PORT}
              --workers ${API_WORKERS}"

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-cpu-worker
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      - diarizer-cache:/tmp/diarizer_cache
    depends_on:
      - redis
    command: >
      celery -A celery_app worker
             --loglevel=info
             --concurrency ${CPU_CONCURRENCY}
             --hostname cpu-worker
             --queues preprocess_cpu

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: proxyai-gpu-worker
    env_file: .env
    depends_on:
      - redis
    runtime: nvidia
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      # bind-mount your host HF cache RW for both reading models and writing quantized files:
      - /path/to/hf_cache_host:/hf_cache:rw
      - ctranslate2-cache:/root/.cache/ctranslate2
    command: >
      celery -A celery_app worker
             --loglevel=info
             --concurrency ${GPU_CONCURRENCY}
             --hostname gpu-worker
             --queues preprocess_gpu

  redis:
    image: redis:7-alpine
    container_name: proxyai-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  tusd:
    image: tusproject/tusd:latest
    container_name: proxyai-tusd
    restart: unless-stopped
    ports:
      - "1080:1080"
    command:
      - tusd
      - --host=0.0.0.0
      - --port=1080
      - --dir=/data
    volumes:
      - upload-data:/data

volumes:
  upload-data:
  results-data:
  diarizer-cache:
  ctranslate2-cache:
  redis-data: