version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
    ports:
      - "8000:8000"
    depends_on:
      - redis

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - DEVICE=cpu
    volumes:
      - upload-data:/tmp/uploads
    depends_on:
      - redis
    command:
      - celery
      - -A
      - celery_app
      - worker
      - -Q
      - preprocess_cpu
      - --concurrency=3
      - --loglevel=info
      - -E

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    restart: always
    env_file: .env
    environment:
      - DEVICE=cuda
    volumes:
      - upload-data:/tmp/uploads
    depends_on:
      - redis
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 4g
    command:
      - celery
      - -A
      - celery_app
      - worker
      - -Q
      - preprocess_gpu
      - --concurrency=1
      - --loglevel=info
      - -E

  flower:
    image: mher/flower:0.9.7
    restart: always
    ports:
      - "5555:5555"
    command:
      - flower
      - --broker=redis://redis:6379/0

volumes:
  upload-data: