version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-api
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FASTAPI_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
    depends_on:
      redis:
        condition: service_healthy
      tusd:
        condition: service_started
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port ${FASTAPI_PORT}
        --workers ${API_WORKERS}

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-cpu-worker
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      - diarizer-cache:/tmp/diarizer_cache
    depends_on:
      redis:
        condition: service_healthy
    command: >
      celery -A celery_app worker
        --loglevel=info
        --concurrency ${CPU_CONCURRENCY}
        --hostname cpu-worker
        --queues preprocess_cpu

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: proxyai-gpu-worker
    env_file: .env
    volumes:
      - upload-data:/tmp/uploads
      - results-data:/tmp/results
      - /path/to/hf_cache_host:/hf_cache:rw
      - ctranslate2-cache:/root/.cache/ctranslate2
    depends_on:
      redis:
        condition: service_healthy
    runtime: nvidia
    command: >
      celery -A celery_app worker
        --loglevel=info
        --concurrency ${GPU_CONCURRENCY}
        --hostname gpu-worker
        --queues preprocess_gpu

  flower:
    image: mher/flower:latest
    container_name: proxyai-flower
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5555:5555"
    command: >
      celery -A celery_app flower
        --port=5555
        --basic_auth=${FLOWER_USER}:${FLOWER_PASS}

  redis:
    image: redis:7-alpine
    container_name: proxyai-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  tusd:
    image: tusproject/tusd:latest
    container_name: proxyai-tusd
    restart: unless-stopped
    ports:
      - "1080:1080"
    command:
      - tusd
      - --host=0.0.0.0
      - --port=1080
      - --dir=/data
    volumes:
      - upload-data:/data

volumes:
  upload-data:
  results-data:
  diarizer-cache:
  ctranslate2-cache:
  redis-data: