version: "3.8"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - redis
      - tusd

  cpu-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency=${CELERY_CONCURRENCY}
      --hostname=cpu-worker
      --queues=preprocess_cpu
    depends_on:
      - redis

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    env_file: .env
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 4G
    command: >
      celery -A celery_app worker
      --loglevel=info
      --concurrency=1
      --hostname=gpu-worker
      --queues=preprocess_gpu
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

  tusd:
    image: tusd/tusd:2.1.0
    ports:
      - "1080:1080"
    command: ["tusd","-port","1080","-dir","/files"]
    volumes:
      - upload-data:/files

volumes:
  redis-data:
  upload-data: