version: "3.8"

services:
  redis:
    image: "redis:7-alpine"
    volumes:
      - redis-data:/data

  tusd:
    image: "tusproject/tusd:latest"
    command: ["tusd", "--dir", "/files", "--no-implicit-create-dir"]
    ports:
      - "1080:1080"
    volumes:
      - upload-data:/files

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-api
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - redis
      - tusd
    volumes:
      - upload-data:/tmp/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyai-worker
    env_file:
      - .env
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - upload-data:/tmp/uploads

volumes:
  redis-data:
  upload-data: