version: "3.9"
services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT:-8000} --workers ${API_WORKERS:-1}
    env_file: .env
    ports:
      - "${FASTAPI_PORT:-8000}:${FASTAPI_PORT:-8000}"
    depends_on:
      - redis
    # не монтируем static/, он уже скопирован в образ

  cpu-worker:
    build:
      context: .
      target: cpu-worker
    command: >
      celery -A celery_app worker
      --concurrency=${CELERY_CONCURRENCY:-1}
      --queues=preprocess_cpu
    env_file: .env
    depends_on:
      - redis

  gpu-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: >
      celery -A celery_app worker
      --concurrency=1
      --queues=preprocess_gpu
    env_file: .env
    # для docker-compose v1.29+:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - hf_cache:/hf_cache
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine

  tusd:
    image: tusproject/tusd:v1.12.0
    # если нужна более новая версия, проверьте тег на Docker Hub

volumes:
  hf_cache: