name: Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy example env
        run: cp .env.example .env

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build all images
        run: docker compose build --no-cache

      - name: Start all services
        run: docker compose up -d --remove-orphans

      - name: Wait for API to be healthy
        run: |
          for i in {1..30}; do
            curl -sf http://localhost:8000/health && exit 0
            sleep 2
          done
          echo "API did not become healthy in time" && exit 1

      - name: Run smoke-test transcription
        run: |
          # здесь ваша команда для smoke-теста
          curl -X POST http://localhost:8000/transcribe \
            -F file="@tests/fixtures/sample.wav" \
            | grep "transcription"

      - name: Tear down services
        if: always()
        run: docker compose down -v